# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A5SlUFsLVi0w02OnfudIOBJUXIt0uQOs
"""

sensor_readings = [45, 78, -12, 90, 105, 66, 88]
def clean_data(readings):
    cleaned = []
    for value in readings:
        if 0 <= value <= 100:
            cleaned.append(value)
    return cleaned

def calculate_average(data):
    if len(data) == 0:
        return 0
    return sum(data) / len(data)

cleaned_readings = clean_data(sensor_readings)
average_value = calculate_average(cleaned_readings)

print("Cleaned Data:", cleaned_readings)
print("Average of Cleaned Data:", average_value)

students = {
    "Ali": [65, 70, 80],
    "Sara": [90, 85, 88],
    "Ahmed": [40, 55, 60]
}
def calculate_average(marks):
    return sum(marks) / len(marks)
def has_passed(average):
    return average >= 50
def display_summary(students):
    for name, marks in students.items():
        avg = calculate_average(marks)
        passed = has_passed(avg)

        print("Student:", name)
        print("Marks:", marks)
        print("Average:", round(avg, 2))

        if passed:
            print("Status: PASSED")
        else:
            print("Status: FAILED")

        print("-----------")

display_summary(students)

class Dataset:
    def __init__(self, values):
        self.values = values
    def count(self):
        return len(self.values)
    def average(self):
        if len(self.values) == 0:
            return 0
        return sum(self.values) / len(self.values)
data_values = [12, 18, 25, 30, 22, 27]
dataset1 = Dataset(data_values)
print("Data:", dataset1.values)
print("Number of data points:", dataset1.count())
print("Average:", dataset1.average())

class SimpleClassifier:
    def __init__(self, threshold):
        self.threshold = threshold

    def classify(self, value):
        return value >= self.threshold

    def classify_list(self, values):
        results = []
        for v in values:
            results.append(self.classify(v))
        return results

threshold = 60
values = [45, 72, 88, 30, 65]

model = SimpleClassifier(threshold)

print("Threshold:", model.threshold)
print("Single Value (72):", model.classify(72))
print("All Values:", model.classify_list(values))

def clean_data(data):
    cleaned = []
    for value in data:
        if 0 <= value <= 100:
            cleaned.append(value)
    return cleaned

class Dataset:
    def __init__(self, values):
        self.values = values

    def count(self):
        return len(self.values)

    def average(self):
        if len(self.values) == 0:
            return 0
        return sum(self.values) / len(self.values)

    def minimum(self):
        if len(self.values) == 0:
            return None
        return min(self.values)

    def maximum(self):
        if len(self.values) == 0:
            return None
        return max(self.values)

raw_data = [10, 55, -3, 78, 120, 66, 92]

cleaned_data = clean_data(raw_data)
dataset = Dataset(cleaned_data)

print("Cleaned Data:", dataset.values)
print("Count:", dataset.count())
print("Average:", round(dataset.average(), 2))
print("Minimum:", dataset.minimum())
print("Maximum:", dataset.maximum())