# -*- coding: utf-8 -*-
"""Lab-Week02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EWZbUEAwDDVnMhSMRiGX3OirvwPgdPD7
"""

#Daily Expense Tracker (Basic)
food = 500
transport = 300
stationery = 100
total_expense = food + transport + stationery
if total_expense >= 1500:
  print ("Montly limit exceed")
else:
  print ("Enjoy! You have enough money")

print ("My total expense is", total_expense)

usage = int(input("Enter data usage in GB: "))

if usage <= 5:
    package = "Basic Package"
elif usage <= 15:
    package = "Standard Package"
else:
    package = "Premium Package"

print("Recommended Package:", package)

temperature = [ 5, 10, 45, 20, 75, 20]
normal_count = 0
high_count = 0
for temp in temperature:
   if 15 <= temp <= 30:
        normal_count += 1
   elif temp > 30:
        high_count += 1
print (f"Normal Temperature:", normal_count)
print (f"High Temperature:", high_count)

incomes = [65000, 45000, 80000, 30000]
status = ["Employed", "Employed", "Employed", "Unemployed"]

eligible = 0

for i in range(len(incomes)):
    if incomes[i] >= 60000 and status[i] == "Employed":
        eligible = eligible + 1

print("Total eligible applicants:", eligible)

# Traffic Speed Analysis
speeds = [60, 85, 90, 75, 100, 80, 70]

violations = 0
total_vehicles = len(speeds)

for speed in speeds:
    if speed > 80:
        violations += 1

percentage = (violations / total_vehicles) * 100

print("Total vehicles:", total_vehicles)
print("Violations:", violations)
print("Violation percentage:", percentage, "%")