# -*- coding: utf-8 -*-
"""lab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-Zd5Wl4BYMlRkBmi5yBXtTkow4Ibw7H
"""

import requests
from bs4 import BeautifulSoup

url = "https://quotes.toscrape.com/page/1/"

response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")

quotes = soup.find_all("div", class_="quote")

quotes_data = []

for q in quotes:
    quote_text = q.find("span", class_="text").text
    author_name = q.find("small", class_="author").text

    quotes_data.append({
        "quote": quote_text,
        "author": author_name
    })

print("Total quotes found:", len(quotes_data))
print()

for item in quotes_data:
    print(item)

import requests
from bs4 import BeautifulSoup

all_quotes = []

for page in range(1, 4):
    url = f"https://quotes.toscrape.com/page/{page}/"

    response = requests.get(url)

    soup = BeautifulSoup(response.text, "html.parser")

    quotes = soup.find_all("div", class_="quote")

    for q in quotes:
        quote_text = q.find("span", class_="text").text
        author_name = q.find("small", class_="author").text

        all_quotes.append({
            "quote": quote_text,
            "author": author_name
        })

print("Total quotes collected:", len(all_quotes))
print()

print("First 5 quotes:\n")
for item in all_quotes[:5]:
    print(item)

import sqlite3

conn = sqlite3.connect("quotes.db")

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS quotes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    quote TEXT,
    author TEXT
)
""")

conn.commit()

print("Database and table created successfully!")

import sqlite3

conn = sqlite3.connect("quotes.db")
cursor = conn.cursor()

cursor.execute("DELETE FROM quotes")
conn.commit()

for item in all_quotes:
    cursor.execute(
        "INSERT INTO quotes (quote, author) VALUES (?, ?)",
        (item["quote"], item["author"])
    )

conn.commit()

print("All scraped quotes inserted into the database successfully!")

import sqlite3

conn = sqlite3.connect("quotes.db")
cursor = conn.cursor()

cursor.execute("SELECT * FROM quotes")
rows = cursor.fetchall()

print("Total stored quotes:", len(rows))
print()

print("First 10 quotes:\n")

for row in rows[:10]:
    print("ID:", row[0])
    print("Quote:", row[1])
    print("Author:", row[2])
    print("-" * 40)

import sqlite3

conn = sqlite3.connect("quotes.db")
cursor = conn.cursor()

author_name = "Albert Einstein"

cursor.execute("SELECT quote, author FROM quotes WHERE author = ?", (author_name,))
author_quotes = cursor.fetchall()

print("Quotes by", author_name + ":\n")
for row in author_quotes:
    print("Quote:", row[0])
    print("Author:", row[1])
    print("-" * 40)

cursor.execute("""
SELECT author, COUNT(*)
FROM quotes
GROUP BY author
ORDER BY COUNT(*) DESC
""")
author_counts = cursor.fetchall()

print("\nQuotes count for each author:\n")
for row in author_counts:
    print(row[0], ":", row[1])

import sqlite3

conn = sqlite3.connect("quotes.db")
cursor = conn.cursor()

author_name = "Albert Einstein"

cursor.execute("""
UPDATE quotes
SET author = UPPER(author)
WHERE author = ?
""", (author_name,))

conn.commit()

print("Author name updated to uppercase successfully!")

cursor.execute("SELECT quote, author FROM quotes WHERE author = ?", ("ALBERT EINSTEIN",))
updated_rows = cursor.fetchall()

print("\nUpdated records:\n")
for row in updated_rows:
    print("Quote:", row[0])
    print("Author:", row[1])
    print("-" * 40)

import sqlite3

conn = sqlite3.connect("quotes.db")
cursor = conn.cursor()

cursor.execute("DELETE FROM quotes WHERE LENGTH(quote) < 30")
conn.commit()

print("Quotes with fewer than 30 characters have been deleted.")

cursor.execute("SELECT * FROM quotes")
rows = cursor.fetchall()
print("\nRemaining quotes count:", len(rows))

import requests
from bs4 import BeautifulSoup
import sqlite3

all_quotes = []

for page in range(1, 4):
    url = f"https://quotes.toscrape.com/page/{page}/"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")
    quotes = soup.find_all("div", class_="quote")
    for q in quotes:
        all_quotes.append({
            "quote": q.find("span", class_="text").text,
            "author": q.find("small", class_="author").text
        })

conn = sqlite3.connect("quotes.db")
cursor = conn.cursor()
cursor.execute("DELETE FROM quotes")
conn.commit()

for item in all_quotes:
    cursor.execute(
        "INSERT INTO quotes (quote, author) VALUES (?, ?)",
        (item["quote"], item["author"])
    )
conn.commit()

cursor.execute("SELECT COUNT(*) FROM quotes")
total_quotes = cursor.fetchone()[0]

cursor.execute("SELECT COUNT(DISTINCT author) FROM quotes")
total_authors = cursor.fetchone()[0]

cursor.execute("""
SELECT author, COUNT(*) as c
FROM quotes
GROUP BY author
ORDER BY c DESC
LIMIT 1
""")
top_author = cursor.fetchone()

print("Total quotes stored:", total_quotes)
print("Total unique authors:", total_authors)
print("Author with the most quotes:", top_author[0], "with", top_author[1], "quotes")

import requests

url = "https://github.com/robots.txt"
response = requests.get(url)

lines = response.text.splitlines()

print("First 20 lines of robots.txt:\n")
for i, line in enumerate(lines[:20], 1):
    print(i, line)

disallowed_dirs = [line.split(": ")[1] for line in lines if line.startswith("Disallow:")]

print("\nDirectories bots should not crawl:")
for dir in disallowed_dirs[:2]:
    print(dir)